### ISSUE TITLE
Maven dependency missing

### ISSUE THREAD

**Issue by madduci** [eID-Testbeds/server#4]
Hi, 

I'm trying to build the project but unfortunately it seems to be broken, because one dependency is missing and not documented:

File: `server/eidsrv-testbed-runner/pom.xml`

```
<!-- Governikus eIDAS Middleware Starterkit -->
<!-- THIS IS A PATCHED VERSION BY SECUNET -->
<dependency>
       <groupId>com.governikus</groupId>
       <artifactId>starterkit</artifactId>
       <version>1.0.1</version>
</dependency>
```

Where can I retrieve this package?

For instance, the [eIDAS-Node-SDK](https://github.com/Governikus/eIDAS-Node-SDK) isn't compatible with this project.

**Comment by sn-pos** [comment]
Hello,

please use the JAR file provided in
/eidsrv-testbed-runner/src/lib/com/governikus/starterkit/1.0.1/starterkit-1.0.1.jar
You might have to adjust your maven installation.

**Comment by madduci** [comment]
Hi @sn-pos 
thanks for answering.
Why hasn't been done something like this?

```
<dependency>
       <groupId>com.governikus</groupId>
       <artifactId>starterkit</artifactId>
       <version>1.0.1</version>
       <scope>system</scope>
       <systemPath>${project.basedir}/src/lib/com/governikus/starterkit/1.0.1/starterkit-1.0.1.jar</systemPath>
</dependency>

```

**Comment by sn-pos** [comment]
Hello @madduci,

there is no particular reason.
Your solution might work, too.
Thanks for sharing it.
